=== bastosbf/mc2-toolset/mc2-gateway-engine/src/main/resources/xsd/modules.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="modules">
    	<xsd:complexType>
            <xsd:all>
            	<xsd:element name="shared-files" maxOccurs="1"
            		minOccurs="1">
            		<xsd:complexType>
            			<xsd:sequence>
            				<xsd:element name="enabled"
            					type="xsd:boolean" minOccurs="1" maxOccurs="1">
            				</xsd:element>
            			</xsd:sequence>
            		</xsd:complexType>
            	</xsd:element>
            	<xsd:element name="public-files" minOccurs="1"
            		maxOccurs="1">
            		<xsd:complexType>
            			<xsd:sequence>
            				<xsd:element name="enabled"
            					type="xsd:boolean" minOccurs="1" maxOccurs="1">
            				</xsd:element>
            			</xsd:sequence>
            		</xsd:complexType>
            	</xsd:element>
            	<xsd:element name="guest-user" minOccurs="1"
            		maxOccurs="1">
            		<xsd:complexType>
            			<xsd:sequence>
            				<xsd:element name="enabled"
            					type="xsd:boolean" minOccurs="1" maxOccurs="1">
            				</xsd:element>
            				<xsd:element name="allowed-versions"
            					minOccurs="1" maxOccurs="1" type="xsd:string">
            				</xsd:element>
            			</xsd:sequence>
            		</xsd:complexType>
            	</xsd:element>
            	<xsd:element name="bulk-jobs" minOccurs="1" maxOccurs="1">
            		<xsd:complexType>
            			<xsd:sequence>
            				<xsd:element name="enabled"
            					type="xsd:boolean" minOccurs="1" maxOccurs="1">
            				</xsd:element>
            				<xsd:element name="begin-value"
            					type="bulk-jobs-valueType" minOccurs="1" maxOccurs="1">
            				</xsd:element>
            				<xsd:element name="end-value"
            					type="bulk-jobs-valueType" minOccurs="1" maxOccurs="1">
            				</xsd:element>
            				<xsd:element name="step-value"
            					type="bulk-jobs-valueType" maxOccurs="1" minOccurs="1">
            				</xsd:element>
            			</xsd:sequence>
            		</xsd:complexType></xsd:element>
            </xsd:all>
    	</xsd:complexType>
    </xsd:element>


    <xsd:complexType name="bulk-jobs-valueType">
    	<xsd:sequence>
    		<xsd:element name="label" type="xsd:string" minOccurs="1" maxOccurs="1"></xsd:element>
    		<xsd:element name="default-value" type="xsd:int" minOccurs="1" maxOccurs="1"></xsd:element>
    	</xsd:sequence>
    	<xsd:attribute name="static" type="xsd:boolean" use="required"></xsd:attribute>
    	<xsd:attribute name="min" type="xsd:int" use="optional"></xsd:attribute>
    	<xsd:attribute name="max" type="xsd:int" use="optional"></xsd:attribute>
    </xsd:complexType>
</xsd:schema>

=== bastosbf/mc2-toolset/mc2-gateway-engine/src/main/resources/conf/modules.xml
<?xml version="1.0" encoding="UTF-8"?>
<modules xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:noNamespaceSchemaLocation="../xsd/modules.xsd">
	<shared-files>
		<enabled>true</enabled>
	</shared-files>
	<public-files>
		<enabled>true</enabled>
	</public-files>
	<guest-user>
		<enabled>true</enabled>
		<allowed-versions>ALL</allowed-versions>
	</guest-user>
	<bulk-jobs>
		<enabled>true</enabled>
		<begin-value static="false" max="10">
			<label>struts.propeties.key</label>
			<default-value>1</default-value>                
		</begin-value>
		<end-value static="false" min="0" max="10">
			<label>End Value</label>
			<default-value>10</default-value>
		</end-value>
		<step-value static="false" min="1">
			<label>Step Value</label>
			<default-value>1</default-value>
		</step-value>
	</bulk-jobs>
</modules>
